name: Setup Node Project
description: Checkout code, setup Node, install dependencies
runs:
  # This action is made up of multiple regular steps, written in plain YAML, and it can be reused across workflows.
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    # better way to cache node_modules folder
    - name: Cache dependencies
      uses: actions/cache@v4
      id: cache
      with:
        path: node_modules # cahced and stored by github
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}        # e.g. id
    - name: Install dependencies
      # bools converted to string value
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
    # - name: Cache dependencies
    #   uses: actions/cache@v4
    #   with:
    #     path: ~/.npm # cahced and stored by github
    #     key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}        # e.g. id
    # - name: Install dependencies
    #   run: npm ci
    #   shell: bash
