# actions are used in steps
name: Setup Node Project & Cache
description: Checkout code, setup Node, install dependencies & Cache
inputs:
  caching:
    description: "Whether to cache deps or not"
    required: true
    default: "true"
outputs:
  executed-at:
    description: Logs when step was executed
    value: ${{ steps.timestamp.outputs.executed-at }}
runs:
  # This action is made up of multiple regular steps, written in plain YAML, and it can be reused across workflows.
  using: "composite"
  steps:
    # checkout can be omissed if it is used online for this repo
    # must be prest if a separate reusable repo
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    # better way to cache node_modules folder
    - name: Cache dependencies
      if: inputs.caching == 'true'
      uses: actions/cache@v4
      id: cache
      with:
        path: node_modules # cahced and stored by github
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }} # e.g. id
    - name: Install dependencies
      # bools converted to string value
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      id: timestamp
      run: |
        npm ci
        echo "executed-at=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
      shell: bash
    # - name: Cache dependencies
    #   uses: actions/cache@v4
    #   with:
    #     path: ~/.npm # cahced and stored by github
    #     key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}        # e.g. id
    # - name: Install dependencies
    #   run: npm ci
    #   shell: bash
