name: Testing Project
# event
on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
  push:
jobs:
  # these jobs run in parallell(if no 'needs' is specified)
  prepa-project:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: setup-up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
  lint-src:
    needs: [prepa-project]
    runs-on: ubuntu-latest
    steps:
      - name: run code formatting test
        run: npm run lint
  test:
    needs: [lint-src]
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: npm ci
      - name: run test
        run: npm test
  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: setup-up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install dependencies
        run: npm ci
      - name: build project
        run: npm run build
      - name: Deploy project
        run: echo "Deployment process is in progress..."    
