name: Testing Project

on:
  pull_request:
    types: [opened, synchronize]
  push:
  workflow_dispatch:

jobs:
  test-code-and-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # 🔥 Required for local actions to be accessible!
      - name: Setup Project
        uses: ./.github/actions/setup-node-project
      - name: Run Lint
        run: npm run lint
      - name: Run Tests
        run: npm test

  deploy:
    needs: test-code-and-formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # 🔥 Required again!
      - name: Setup Project
        uses: ./.github/actions/setup-node-project
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: echo "Deployment process is in progress..."
