name: First Workflow
# event(s)
on: workflow_dispatch
# tasks to do
jobs:
  # job name
  first-job:
    # os to run on
    runs-on: ubuntu-latest
    # steps to do for this job
    steps:
      # name of the step
      - name: Print greeting
        # what to do for this step
        run: echo "Hi there!"
      - name: Print goodbey
        run: echo "bye!"
      
