name: Matrix Demo

on: 
  push:

jobs:
  build:
    continue-on-error: true
    strategy:
        matrix:
            node-version: [14,16,18]
            os: [ubuntu-latest, windows-latest]
            include:
              - node-version: 20
                operating-system: ubuntu-latest
            exclude:
              - node-version: 14
                operating-system: windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Deps
        run: npm ci

      - name: Build Project
        run: npm run build