name: Reusable Workflow
on: 
  workflow_call:
    # used to receive file from caller .yml file
    inputs:
      script-file:
        required: true
        type: string
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Get build artifacts
            uses: actions/download-artifact@v4
            with:
              name: dist-files # downloading
          - name: Output contents
            run: ls -la
          - name: Output filename
            run: echo "${{ needs.build.outputs.script-file }}"
          - name: Deploy
            run: echo "Deployment process is in progress..."
          - name: Info Output
            run: echo "${{toJson(github)}}"
              