name: Reusable Workflow
on: 
  workflow_call:
    # used to receive file from caller .yml file
    inputs:
      script-file:
        required: true
        type: string
        description: The index file of your project
      dist-name:
        required: true
        type: string
        default: dist
        description: build files of your project

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Get build artifacts
            uses: actions/download-artifact@v4
            with:
              name: ${{ inputs.dist-name }} # downloading file by specified named stored before
          - name: Output contents
            run: ls -la
          - name: Output filename
            run: > # or |
              echo "Script file: ${{ inputs.script-file }}"
          - name: Deploy
            run: echo "Deployment process is in progress..."
          - name: Info Output
            run: echo "${{toJson(github)}}"
              